vegaEmbed('#vis1', 'specs/01_choropleth.json', {actions: false});
vegaEmbed('#vis2', 'specs/02_bump.json', {actions: false, renderer: 'svg'});
vegaEmbed('#vis3', 'specs/03_connected.json', {actions: false, renderer: 'svg'});
vegaEmbed('#vis4', 'specs/04_flowmap.json', {actions: false, renderer: 'svg'});
vegaEmbed('#vis5', 'specs/05_streamgraph.json', {actions: false, renderer: 'svg'});
vegaEmbed('#vis6', 'specs/06_symbolmap.json', {actions: false, renderer: 'svg'});
vegaEmbed('#vis7', 'specs/07_heatmap.json', {actions: false, renderer: 'svg'});
vegaEmbed('#vis8', 'specs/08_spikemap.json', {actions: false, renderer: 'svg'});
vegaEmbed('#vis9', 'specs/09_slope.json', {actions: false, renderer: 'svg'});
vegaEmbed('#vis10', 'specs/10_ridgeline.json', {actions: false, renderer: 'svg'});
vegaEmbed('#vis11', 'specs/11_violin.json', {actions: false, renderer: 'svg'});